/**
 * Packs every asset the office needs into one generated TS module of base64 PNGs + JSON, so the
 * Vite lazy chunk has no network dependencies. Upstream assets come from
 * pixel-agents-hq/pixel-agents webview-ui/public/assets (copied to ../upstream-assets); the furniture
 * catalog is built with upstream's own core/src/assets/build.ts. Trunk sheets come from
 * scripts/trunk_sprites.py (../branch-assets/trunks).
 *
 * Run from the repository root: node --import ./engine/scripts/tsx.mjs window/src/places/office/pixel/scripts/build-assets.ts
 */
import * as fs from 'fs';
import * as path from 'path';

import { PNG } from 'pngjs';

import { buildFurnitureCatalog } from '../core/src/assets/build.ts';

const ROOT = path.resolve(import.meta.dirname, '..');
const UP = path.join(ROOT, 'upstream-assets');
const BR = path.join(ROOT, 'branch-assets');
const OUT = path.join(ROOT, 'webview-ui/src/branch/generated/assets.gen.ts');

/** Base64 of a PNG re-encoded without its ancillary chunks (upstream PNGs carry Photoshop XMP). */
const b64 = (p: string): string => {
  const buf = fs.readFileSync(p);
  try {
    const clean = PNG.sync.write(PNG.sync.read(buf), { colorType: 6 });
    return (clean.length < buf.length ? clean : buf).toString('base64');
  } catch {
    return buf.toString('base64');
  }
};
const raw64 = (p: string): string => fs.readFileSync(p).toString('base64');
const sortedPngs = (dir: string, re: RegExp): string[] =>
  fs
    .readdirSync(dir)
    .filter((f) => re.test(f))
    .sort((a, b) => Number(re.exec(a)![1]) - Number(re.exec(b)![1]))
    .map((f) => path.join(dir, f));

const catalog = buildFurnitureCatalog(UP);
const furniturePngs: Record<string, string> = {};
for (const e of catalog) furniturePngs[e.furniturePath] = b64(path.join(UP, e.furniturePath));

const pets = fs
  .readdirSync(path.join(UP, 'pets'))
  .sort()
  .map((id) => ({
    ...(JSON.parse(fs.readFileSync(path.join(UP, 'pets', id, 'manifest.json'), 'utf8')) as {
      id: string;
      name: string;
    }),
    png: b64(path.join(UP, 'pets', id, 'pet.png')),
  }));

// Branch's pets (scripts/pet_sprites.py) after upstream's two, in upstream's 96×96 pet-sheet format.
const branchPetDir = path.join(BR, 'pets');
for (const p of JSON.parse(fs.readFileSync(path.join(branchPetDir, 'pets.json'), 'utf8')) as Array<{ id: string; name: string }>) {
  pets.push({ ...p, png: b64(path.join(branchPetDir, `${p.id}.png`)) });
}

const trunkDir = path.join(BR, 'trunks');
const trunkMeta = JSON.parse(fs.readFileSync(path.join(trunkDir, 'trunks.json'), 'utf8'));
const trunkPngs: Record<string, string> = {};
for (const f of fs.readdirSync(trunkDir).filter((f) => f.endsWith('.png'))) {
  trunkPngs[f.replace(/\.png$/, '')] = b64(path.join(trunkDir, f));
}

const data = {
  characters: sortedPngs(path.join(UP, 'characters'), /^char_(\d+)\.png$/).map(b64),
  floors: sortedPngs(path.join(UP, 'floors'), /^floor_(\d+)\.png$/).map(b64),
  walls: sortedPngs(path.join(UP, 'walls'), /^wall_(\d+)\.png$/).map(b64),
  carpets: sortedPngs(path.join(UP, 'carpets'), /^carpet_(\d+)\.png$/).map(b64),
  catalog,
  furniturePngs,
  pets,
  trunkMeta,
  trunkPngs,
  font: raw64(path.join(BR, 'fs-pixel-sans-subset.woff2')),
};

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  '// GENERATED by scripts/build-assets.ts. Do not edit.\n' +
    '/* eslint-disable */\n' +
    'export interface TrunkMeta { cellW: number; cellH: number; frames: number; rows: string[]; looks: Array<{ id: string; name: string; description: string; states: string[] }>; pebble: { states: string[]; shapes: number; eyes: string[] } }\n' +
    'export interface AssetBundle { characters: string[]; floors: string[]; walls: string[]; carpets: string[]; catalog: unknown[]; furniturePngs: Record<string, string>; pets: Array<{ id: string; name: string; png: string }>; trunkMeta: TrunkMeta; trunkPngs: Record<string, string>; font: string }\n' +
    `export const ASSETS: AssetBundle = ${JSON.stringify(data)};\n`,
);
console.log(`[build-assets] wrote ${OUT} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
