export const browserCoreExamples = [
  "branch browser status",
  "branch browser start",
  "branch browser start --headless",
  "branch browser stop",
  "branch browser tabs",
  "branch browser open https://example.com",
  "branch browser focus abcd1234",
  "branch browser close abcd1234",
  "branch browser screenshot",
  "branch browser screenshot --full-page",
  "branch browser screenshot --ref 12",
  "branch browser snapshot",
  "branch browser snapshot --format aria --limit 200",
  "branch browser snapshot --efficient",
  "branch browser snapshot --labels",
];

export const browserActionExamples = [
  "branch browser navigate https://example.com",
  "branch browser resize 1280 720",
  "branch browser click 12 --double",
  "branch browser click-coords 120 340",
  'branch browser type 23 "hello" --submit',
  "branch browser press Enter",
  "branch browser hover 44",
  "branch browser drag 10 11",
  "branch browser select 9 OptionA OptionB",
  "branch browser upload /tmp/branch/uploads/file.pdf",
  "branch browser upload media://inbound/file.pdf",
  'branch browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "branch browser dialog --accept",
  'branch browser wait --text "Done"',
  "branch browser evaluate --fn '(el) => el.textContent' --ref 7",
  "branch browser evaluate --fn 'const title = document.title; return title;'",
  "branch browser console --level error",
  "branch browser pdf",
  "branch browser batch --actions-file plan.json",
  'branch browser batch --actions \'[{"kind":"wait","timeMs":500},{"kind":"click","ref":"12"},{"kind":"type","ref":"23","text":"hello"}]\'',
  "branch browser batch --actions-file plan.json --continue",
];
