// TODO(engine-lane): the greyed reasons in this file say what is still missing; shownWhy (shell/shown-why.ts) keeps them out of sight.
import { useState } from "react";
import type { ReactNode } from "react";
import type { SettingsPageProps } from "./index";
import { at, list, record, text, visible } from "./adapter";
import type { RecordValue } from "./adapter";
import { useResource } from "./hooks";
import { useBranchVersion, versionParts } from "../../connect/branch-version";

function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h2>{title}</h2>{children}</section>; }
function State({ loading, error }: { loading: boolean; error?: string }) { return loading ? <p role="status">Loading from the engine.</p> : error ? <p className="bs-error" role="alert">{visible(error)}</p> : null; }
function Row({ title, note, children }: { title: string; note?: ReactNode; children?: ReactNode }) { return <div className="bs-row"><span className="bs-grow"><span className="bs-label">{title}</span>{note && <small>{note}</small>}</span>{children}</div>; }
function Badge({ children, good }: { children: ReactNode; good?: boolean }) { return <span className={`bs-chip${good ? " bs-connected" : ""}`}>{children}</span>; }
function date(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? new Date(value).toLocaleString() : "Not reported"; }
function count(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value.toLocaleString() : "Not reported"; }
function money(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value) : "Not reported"; }
export function remainingPercent(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 100 ? 100 - value : undefined; }

/** Source: provider-usage.types.ts; percentages are provider values, never invented quotas. */
export function UsageSettings({ engine, level }: SettingsPageProps) {
  const [days, setDays] = useState(30);
  const usage = useResource<RecordValue>(engine, "usage.status");
  const costs = useResource<RecordValue>(engine, "usage.cost", { days, ...(engine.agentId ? { agentId: engine.agentId } : {}) });
  const providers = list(usage.data?.providers); const totals = record(costs.data?.totals);
  const cache = record(costs.data?.cacheStatus);
  return <><div className="bs-spend-card"><div><small>Last {days} days</small><strong className="bs-big-number">{costs.loading ? "Loading" : costs.error ? "Unavailable" : money(totals.totalCost)}</strong><small>{totals.totalTokens === undefined ? "Recorded conversation costs" : `${count(totals.totalTokens)} tokens · recorded conversation costs`}</small></div><div className="bs-tabs" role="group" aria-label="Spend period">{[7,30,90].map(value => <button key={value} aria-pressed={days === value} onClick={() => setDays(value)}>{value} days</button>)}</div><button disabled={costs.loading} onClick={() => void costs.reload()}>Refresh spend</button></div><State loading={false} error={costs.error} />
    {cache.status && cache.status !== "fresh" && <p role="status">Cost records are {text(cache.status)}. {count(cache.pendingFiles)} files are awaiting refresh; totals may be incomplete.</p>}
    {typeof totals.missingCostEntries === "number" && totals.missingCostEntries > 0 && <p>{count(totals.missingCostEntries)} records have no price information. The displayed cost excludes those unknown amounts.</p>}
    <Section title="What each connection has left"><p>How much of each service's allowance is still there. Every figure comes from the connected service.</p><State {...usage} />{usage.data?.refreshing === true && <p role="status">The engine is refreshing provider allowances. Refresh this page for the completed values.</p>}
      {usage.data && !providers.length && usage.data.refreshing !== true && <p>No service allowances were reported. Connect a model account to see the usage its service provides.</p>}
      {providers.map((provider, index) => <article className="bs-provider" key={`${text(provider.provider)}-${index}`}><div className="bs-provider-head"><span className="bs-service-icon" aria-hidden="true">{visible(provider.displayName ?? provider.provider).slice(0,1)}</span><b>{visible(provider.displayName ?? provider.provider)}</b>{provider.plan != null && <small>{visible(provider.plan)}</small>}{provider.accountEmail != null && <small>{visible(provider.accountEmail)}</small>}{!provider.error && <Badge good>Service reported</Badge>}</div>
        {provider.error ? <p className="bs-error" role="alert">{visible(provider.error)}</p> : <>{list(provider.windows).map((window, i) => { const remaining = remainingPercent(window.usedPercent); return <div className="bs-quota" key={i}><span>{visible(window.label)}</span>{remaining === undefined ? <span>Allowance not reported</span> : <><span className="bs-meter" role="meter" aria-label={`${visible(window.label)} remaining`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={remaining}><i style={{ width: `${remaining}%` }} /></span><span>{Number(remaining.toFixed(1))}% left{window.resetAt != null ? ` · resets ${date(window.resetAt)}` : ""}</span></>}</div>; })}{!list(provider.windows).length && <p>{provider.summary ? visible(provider.summary) : "This service did not report an allowance window."}</p>}{list(provider.billing).map((billing,i) => <p key={i}>{visible(billing.label ?? billing.type)}: {billing.type === "budget" ? `${count(billing.used)} / ${count(billing.limit)}` : count(billing.amount)} {visible(billing.unit)}{billing.period ? ` · ${visible(billing.period)}` : ""}</p>)}</>}
      </article>)}{usage.data?.updatedAt != null && <small>Updated {date(usage.data.updatedAt)}</small>}<div className="bs-actions"><button disabled={usage.loading} onClick={() => void usage.reload()}>Refresh allowances</button></div></Section>
    <Section title={`Spend, last ${days} days`}>{costs.data && <><div className="bs-row"><span className="bs-label">Recorded cost</span><b>{money(totals.totalCost)}</b></div>{list(costs.data.daily).map(day => <Row key={text(day.date)} title={text(day.date)} note={day.totalTokens == null ? undefined : `${count(day.totalTokens)} tokens`}><span>{money(day.totalCost)}</span></Row>)}{!list(costs.data.daily).length && <p>No daily cost records were reported in this period.</p>}<small>Costs use the engine's recorded model prices. Subscription plans are billed by their own services. {engine.agentId ? `Showing ${visible(engine.agentId)}.` : "Showing the gateway's default Trunk."}</small></>}{level === "technical" && costs.data?.updatedAt != null && <small>Cost cache updated {date(costs.data.updatedAt)}</small>}</Section>
  </>;
}

/** Source: desktop/computer-service.ts and shared/node-list-types.ts. */
export function ComputerSettings({ engine, level }: SettingsPageProps) {
  const computer = useResource<RecordValue>(engine, "computer.status"); const nodes = useResource<RecordValue>(engine, "node.list");
  const capability = record(computer.data?.computerUse); const provider = record(capability.provider); const computers = list(nodes.data?.nodes);
  const pending = computers.filter(node => node.approvalState === "pending-approval" || node.approvalState === "pending-reapproval");
  return <>{pending.length > 0 && <Section title="Waiting for your yes"><p>Only allow a computer you recognise. Pairing and permission changes use the engine's approval flow.</p>{pending.map(node => <Row key={text(node.nodeId)} title={visible(node.displayName ?? node.nodeId)} note={`${visible(node.platform)} · ${visible(node.approvalState)}`}><Badge>Waiting for approval</Badge></Row>)}</Section>}
    <Section title="Computers they may use"><State {...computer} />{computer.data && <Row title="This computer" note={computer.data.error ? visible(computer.data.error) : computer.data.configured === true ? `${visible(provider.label ?? provider.id ?? "Computer tools")} · configured in the engine` : "Computer control has not been configured in this engine."}><Badge good={computer.data.available === true}>{computer.data.available === true ? "Available" : "Unavailable"}</Badge></Row>}<State {...nodes} />{computers.filter(node => !pending.includes(node)).map(node => <article className="bs-node-card" key={text(node.nodeId)}><div className="bs-node-head"><span className="bs-service-icon" aria-hidden="true">▣</span><span className="bs-grow"><b>{visible(node.displayName ?? node.nodeId)}</b><small>{visible(node.platform ?? "Platform not reported")}{node.version ? ` · ${visible(node.version)}` : ""}{node.gatewayLocal ? " · on this computer" : ""}</small></span><Badge good={node.connected === true}>{node.connected === true ? "Online" : "Offline"}</Badge></div>{node.active === true && <small>Currently active</small>}{Array.isArray(node.caps) && <small>{node.caps.map(visible).join(" · ")}</small>}{node.lastSeenAtMs != null && <small>Last seen {date(node.lastSeenAtMs)}</small>}{level === "technical" && <small>{text(node.nodeId)}</small>}{list(node.issues).map((issue,i) => <p className="bs-error" key={i}>{visible(issue.message ?? issue.code)}</p>)}</article>)}{nodes.data && !computers.length && <p>No paired computers were reported by the engine.</p>}<div className="bs-actions"><button disabled={computer.loading || nodes.loading} onClick={() => { void computer.reload(); void nodes.reload(); }}>Refresh computers</button></div></Section>
    <Section title="The browser"><Row title="Browser control" note={Array.isArray(capability.actions) ? capability.actions.some(action => typeof action === "string" && action.startsWith("browser_")) ? "Browser actions are available through the computer provider." : "This computer provider does not report browser actions." : "Browser capability has not been reported by this engine."}><Badge good={Array.isArray(capability.actions) && capability.actions.some(action => typeof action === "string" && action.startsWith("browser_"))}>{Array.isArray(capability.actions) && capability.actions.some(action => typeof action === "string" && action.startsWith("browser_")) ? "Available" : "Not reported"}</Badge></Row></Section>
  </>;
}

/** Source: health.ts, health/types.ts, server/process-vitals.ts, status/summary.ts. */
export function GatewaySettings({ engine, level }: SettingsPageProps) {
  const version = useBranchVersion(engine.gatewayUrl);
  const health = useResource<RecordValue>(engine, "health", { probe: false }); const status = useResource<RecordValue>(engine, "status");
  const channels = record(health.data?.channels);
  return <><State {...health} />{health.data && <div className="bs-status-card"><span className="bs-status-dot" /><span><b>The gateway is connected</b><p>{typeof health.data.durationMs === "number" ? `Health check answered in ${health.data.durationMs} ms.` : "The engine answered the health check."}{health.data.ts != null ? ` Checked ${date(health.data.ts)}.` : ""}</p></span></div>}
    <Section title="Keep Branch running"><Row title="Gateway" note="This window is connected to the gateway started by the desktop launcher."><Badge good={!!health.data}>{health.data ? "Connected" : health.loading ? "Checking" : "Unavailable"}</Badge></Row><Row title="Background service & tray" note="Start with Windows and closing to the tray are in General; the tray’s usage ring is in Usage. They are set by the Branch app on this computer." /></Section>
    <Section title="What it has been doing"><State {...status} /><Row title="Health check" note={health.data?.ts != null ? `Checked ${date(health.data.ts)}` : "Not checked"}><span>{typeof health.data?.durationMs === "number" ? `${health.data.durationMs} ms` : "Not reported"}</span></Row>{Object.entries(channels).map(([id, value]) => { const channel = record(value); return <Row key={id} title={visible(record(health.data?.channelLabels)[id] ?? id)} note={channel.lastError ? visible(channel.lastError) : undefined}><Badge good={channel.connected === true}>{channel.connected === true ? "Connected" : channel.running === true ? "Running" : channel.configured === false ? "Not configured" : "Not connected"}</Badge></Row>; })}{version && <Row title="Branch version"><span>{versionParts(version).detail}</span></Row>}{at(status.data,"modelRuntime.status") != null && <Row title="Model runtime"><span>{visible(at(status.data,"modelRuntime.status"))}</span></Row>}
    {level === "technical" && <><Row title="Engine process"><span>{status.data?.pid == null ? "Not reported" : text(status.data.pid)}</span></Row><Row title="Memory in use"><span>{typeof at(status.data,"processMemory.rssBytes") === "number" ? `${(Number(at(status.data,"processMemory.rssBytes"))/1024/1024).toFixed(1)} MB` : "Not reported"}</span></Row></>}
    <div className="bs-actions"><button disabled={health.loading || status.loading} onClick={() => { void health.reload(); void status.reload(); }}>Check gateway</button></div><small>Recovery history and restart controls require the desktop supervisor adapter. No example events are shown as real activity.</small></Section>
  </>;
}

export function LocalModelSettings({ engine, openSettings }: SettingsPageProps) {
  const models = useResource<RecordValue>(engine, "models.list", {includeDetails:true,preparedOnly:true});
  const local = list(models.data?.models).filter(model => model.local === true);
  return <Section title="On this computer"><State {...models} />{models.data && !local.length && <p>No local models were reported by the engine. Connect a local runtime before choosing a model to run here.</p>}{local.map(model => <Row key={`${text(model.provider)}/${text(model.id)}`} title={visible(model.name ?? model.id)} note={`${visible(model.provider)}${typeof model.contextWindow === "number" ? ` · ${count(model.contextWindow)} context tokens` : ""}`}><Badge good={model.available === true}>{model.available === false ? "Unavailable" : model.available === true ? "Available" : "Availability not reported"}</Badge></Row>)}<div className="bs-actions"><button disabled={models.loading} onClick={() => void models.reload()}>Refresh local models</button>{openSettings && <button onClick={() => openSettings("accounts")}>Open Accounts</button>}</div><small>Installing or downloading a runtime uses its provider setup flow. This page reads the engine's prepared local model catalog.</small></Section>;
}
